CFLAGS = -DJIVELITE -s -O2 -fPIC -I../../src -I$(PREFIX)/include/SDL -I$(PREFIX)/include -I$(PREFIX)/include/luajit-$(LUAJIT_VERSION)
LDFLAGS = -s -L$(PREFIX)/lib -llirc_client -Wl,-rpath,$(PREFIX)/lib

MODULE := ir_bsp.so

all: $(MODULE)

$(MODULE): ir.o ir_bsp.o
	$(CC) $^ -shared $(LDFLAGS) -o $@

.c.o:
	$(CC) $(CFLAGS) -c -o $@ $^

clean:
	rm -f *.o $(MODULE)
